Caracteres comuns
? Caracteres mais comuns na escrita segundo a classificação em http://hanzidb.org/character-list/by-frequency
@gabs-courses/pt-zh/ser-estar.module
@gabs-courses/pt-zh/numeros_1.module
@gabs-courses/pt-zh/comida_1.module

Lição 1
? grande: 大
? negação: 不
? ação completa / intensificador: 了
? estar morto: 不在了
? possessivo ou suffixo de adjetivo: 的
grande -> 大
negação -> 不
ação completa / intensificador -> 了
estar morto -> 不在了
possessivo ou suffixo de adjetivo -> 的

Lição 2
? central, meio: 中
? cima, superior, subir: 上
? fazer, gerenciar: 为
? adjetivo numeral: 个
? por, para: 以
central, meio -> 中
cima, superior, subir -> 上
fazer, gerenciar -> 为
adjetivo numeral -> 个
por, para -> 以
[@numero@pl=pluralidade@g=genero] [@fruta@pluralidade=pl@genero=g] -> [0]个[1]

Lição 3
? ir, chegar: 到
? voltar: 来
? nação, país: 国
? terra: 地
? paz: 和
ir, chegar  -> 到
voltar      -> 来
nação, país -> 国
terra       -> 地
paz         -> 和

Lição 4
? dizer, falar: 说
? sair, mandar: 出
? reunir: 会
? permitir: 可
? poder: 能
dizer, falar -> 说
sair, mandar -> 出
reunir       -> 会
permitir     -> 可
poder        -> 能

Lição 5
? e, mas: 而
? também, sim: 也
? debaixo: 下
? dentro: 于
? certo, oposto: 对
e | mas -> 而
também | sim! -> 也
debaixo -> 下
dentro -> 于
certo | oposto -> 对
